
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rodkrpeqxgqizngdypbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvZGtycGVxeGdxaXpuZ2R5cGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDY5ODEsImV4cCI6MjA2MDcyMjk4MX0.ECPKii1lST8GcNt0M8SGXKLeeyJSL6vtIpoXVH5SZYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" && localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper function to clean up authentication state
// This helps prevent auth "limbo" states
export const cleanupAuthState = () => {
  // Remove standard auth tokens
  typeof window !== "undefined" && localStorage.removeItem('supabase.auth.token');
  
  // Remove all Supabase auth keys from typeof window !== "undefined" && localStorage
  Object.keys(typeof window !== "undefined" && localStorage).forEach((key) => {
    if (key.startsWith('supabase.auth.') || key.includes('sb-')) {
      typeof window !== "undefined" && localStorage.removeItem(key);
    }
  });
  
  // Remove from typeof window !== "undefined" && sessionStorage if in use
  Object.keys(typeof window !== "undefined" && sessionStorage || {}).forEach((key) => {
    if (key.startsWith('supabase.auth.') || key.includes('sb-')) {
      typeof window !== "undefined" && sessionStorage.removeItem(key);
    }
  });
};
